api/urls.py
# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from api import views

api_router = routers.DefaultRouter()
api_router.register(r"events", views.EventViewSet, basename="events")
api_router.register(r"formats", views.ListFormats, basename="formats")
api_router.register(r"organizers", views.OrganizersViewSet, basename="organizers")

urlpatterns = [
    path("", include(api_router.urls)),
    path("auth/", obtain_auth_token, name="api_auth_token"),
]

articles/urls.py
# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.urls import path

from articles.views import (
    ArticleAddView,
    ArticleArchiveView,
    ArticleAttachmentCreateView,
    ArticleDraftView,
    ArticlePreviewView,
    ArticleUpdateView,
    ArticleView,
)

urlpatterns = [
    path("", ArticleArchiveView.as_view(), name="article-list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/",
        ArticleView.as_view(),
        name="article-details",
    ),
    path(
        "preview/<int:pk>/<slug:slug>/",
        ArticlePreviewView.as_view(),
        name="article-preview",
    ),
    path(
        "edit/<int:pk>/<slug:slug>/",
        ArticleUpdateView.as_view(),
        name="article-update",
    ),
    path(
        "create/",
        ArticleAddView.as_view(),
        name="article-create",
    ),
    path(
        "drafts/",
        ArticleDraftView.as_view(),
        name="article-drafts",
    ),
    path(
        "attachment/",
        ArticleAttachmentCreateView.as_view(),
        name="article-attachment-create",
    ),
]

mtg_championship_site/urls.py
# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""mtg_championship_site URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("championship.urls")),
    path("api/", include("api.urls")),
    path("invoicing/", include("invoicing.urls")),
    path("decklists/", include("decklists.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("django_prometheus.urls")),
    path("__debug_toolbar__/", include("debug_toolbar.urls")),
    path("hijack/", include("hijack.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("media/", include("file_storage_db.urls")),
]

swiss_unity_league_site/urls.py
# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("championship.urls")),
    path("", include("robotstxt.urls")),
    path("api/", include("api.urls")),
    path("invoicing/", include("invoicing.urls")),
    path("decklists/", include("decklists.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("django_prometheus.urls")),
    path("__debug_toolbar__/", include("debug_toolbar.urls")),
    path("hijack/", include("hijack.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("media/", include("file_storage_db.urls")),
    path("articles/", include("articles.urls")),
    path("info/", include("info.urls")),
    path("legal/", include("legal.urls")),
]

articles/models.py
# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf import settings
from django.core.cache import cache
from django.core.cache.utils import make_template_fragment_key
from django.core.validators import validate_image_file_extension
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.forms import ValidationError
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from django_bleach.models import BleachField


class ArticleManager(models.Manager):
    def published(self):
        today = timezone.now().date()
        return self.filter(published_date__lte=today)

    def non_published(self):
        today = timezone.now().date()
        return self.exclude(published_date__lte=today)


def article_image_validator(image):
    if image.size > 0.5 * 1024 * 1024:
        raise ValidationError("Image file too large ( > 500KB )")


class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    last_changed = models.DateTimeField(auto_now=True)
    published_date = models.DateField(
        null=True,
        blank=True,
        help_text="The date at which an article was published. Can be in the future for scheduled publishing.",
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    content = BleachField(
        help_text="The article's content. Supports the following HTML tags: {}".format(
            ", ".join(settings.BLEACH_ALLOWED_TAGS_ARTICLE)
        ),
        blank=True,
        strip_tags=True,
        allowed_tags=settings.BLEACH_ALLOWED_TAGS_ARTICLE,
    )
    description = models.TextField(
        help_text="A short description that advertises the article. Used on the homepage and in meta data.",
        blank=True,
        max_length=200,
    )
    header_image = models.ImageField(
        upload_to="article_header",
        help_text="The advertisment image for the home page. Maximum size: 500KB. Supported formats: JPEG, PNG, WEBP.",
        blank=True,
        null=True,
        validators=[article_image_validator, validate_image_file_extension],
    )

    def __str__(self):
        return f"{self.title} (by {self.author})"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        if self.published_date and self.published_date <= timezone.now().date():
            return reverse(
                "article-details",
                args=[
                    self.published_date.year,
                    self.published_date.month,
                    self.published_date.day,
                    self.slug,
                ],
            )

        return reverse(
            "article-preview",
            args=[
                self.id,
                self.slug,
            ],
        )

    objects = ArticleManager()


@receiver(post_save, sender=Article)
def invalidate_article_cache(sender, instance, **kwargs):
    key = make_template_fragment_key("article_content", [instance.id])
    cache.delete(key)

oracle/models.py
# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import uuid

from django.db import models


class Card(models.Model):
    class Meta:
        indexes = [models.Index(fields=["name"])]

    oracle_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=128)
    mana_cost = models.CharField(max_length=64, blank=True)
    scryfall_uri = models.CharField(max_length=128)
    mana_value = models.IntegerField()
    type_line = models.CharField(max_length=128)
    image_uri = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class AlternateName(models.Model):
    class Meta:
        indexes = [models.Index(fields=["name"])]

    name = models.CharField(max_length=128)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)


def get_card_by_name(name: str, exact_match=False) -> Card:
    if exact_match:
        filter = {"name": name}
    else:
        filter = {"name__iexact": name}
    try:
        return Card.objects.get(**filter)
    except Card.DoesNotExist as e:
        try:
            return AlternateName.objects.get(**filter).card
        except AlternateName.DoesNotExist:
            raise e

articles/forms.py
# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django import forms
from django.conf import settings

from tinymce.widgets import TinyMCE

from articles.models import Article
from championship.forms import SubmitButtonMixin


class ArticleUpdateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = [
            "title",
            "content",
            "published_date",
            "header_image",
            "description",
        ]
        widgets = {
            "published_date": forms.DateInput(attrs={"type": "date"}),
            "content": TinyMCE(
                mce_attrs={
                    "toolbar": "undo redo | h2 h3 h4 | bold italic | link unlink | bullist numlist",
                    "link_assume_external_targets": "http",
                },
            ),
        }
        help_texts = {
            "content": """Supports the following HTML tags: {}.
To reference a card wrap it in brackets (e.g. [[Daze]]). To reference a decklist just paste a unityleague link.
To add an image, use this syntax (including the exclamation mark): "![Image title](https://unityleague.ch/static/flag.png)".
""".format(
                ", ".join(settings.BLEACH_ALLOWED_TAGS_ARTICLE)
            ),
        }


class AttachmentUploadForm(forms.Form, SubmitButtonMixin):
    file = forms.FileField(required=True, help_text="The file to upload.")

articles/views.py
# Copyright 2024 Leonin League
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import reverse
from django.views.generic import DetailView, ListView
from django.views.generic.dates import ArchiveIndexView, DateDetailView
from django.views.generic.edit import CreateView, FormView, UpdateView

from articles.forms import ArticleUpdateForm, AttachmentUploadForm
from articles.models import Article
from file_storage_db.models import File


class ArticleArchiveView(ArchiveIndexView):
    model = Article
    date_field = "published_date"
    context_object_name = "articles"


class ArticleView(DateDetailView):
    model = Article
    date_field = "published_date"
    year_format = "%Y"
    month_format = "%m"
    day_format = "%d"


class ArticlePreviewView(DetailView):
    model = Article
    query_pk_and_slug = True


class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = "articles.change_article"
    model = Article
    query_pk_and_slug = True
    template_name = "articles/update_article.html"
    form_class = ArticleUpdateForm


class ArticleAddView(PermissionRequiredMixin, CreateView):
    permission_required = "articles.add_article"
    template_name = "articles/update_article.html"
    model = Article
    form_class = ArticleUpdateForm

    def form_valid(self, form: ArticleUpdateForm):
        # We assume the author is the person creating the article for the first
        # time. If it is ever needed to change this, it can be done through the
        # admin panel.
        form.instance.author = self.request.user
        return super().form_valid(form)


class ArticleDraftView(PermissionRequiredMixin, ListView):
    permission_required = "articles.add_article"
    model = Article
    template_name = "articles/article_draft.html"
    context_object_name = "articles"
    ordering = "-last_changed"

    def get_queryset(self):
        return Article.objects.non_published().filter(author=self.request.user)


class ArticleAttachmentCreateView(
    PermissionRequiredMixin, SuccessMessageMixin, FormView
):
    permission_required = "articles.add_article"
    form_class = AttachmentUploadForm
    template_name = "articles/upload_attachment.html"

    def form_valid(self, form):
        file = form.cleaned_data["file"]
        path = f"articles/{file.name}"

        # In-DB storage does not support writing for now
        # TODO: Unique filename
        # TODO: Use Django's Storage API here
        self.db_file, _ = File.objects.get_or_create(filename=path)
        self.db_file.content = b"".join(file.chunks())
        self.db_file.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("article-attachment-create")

    def get_success_message(self, cleaned_data):
        url = self.request.build_absolute_uri(
            f"/{settings.MEDIA_URL}/{self.db_file.filename}"
        )
        return f"Your file is now available at {url}"

articles/templates/articles/article_archive.html
{% extends 'championship/base.html' %}

{% block title %}Articles{% endblock %}
{% load custom_tags %}


{% block content %}
    <h1>Articles</h1>

    <div class="row gx-4 gx-lg-5">
        {% for article in articles %}
            {% include "articles/article_card.html" %}
        {% endfor %}
    </div>
{% endblock %}

articles/templates/articles/article_card.html
{% load custom_tags %}
{% load waffle_tags %}

<div class="col-lg-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{ article.title }}</h2>
            <p class="card-subtitle text-muted mb-2">
                <span>by {{ article.author.first_name }} {{ article.author.last_name }}</span>
                | <span>{{ article.published_date|weekday_date }}</span>
            </p>
            {% flag "index_article_card_show_header" %}
                {% if article.header_image %}
                    <img src="{{ article.header_image.url }}" class="card-img-top" alt="Article Image">
                {% else %}
                    <p class="card-text">
                        {% if article.description %}
                            {{ article.description }}
                        {% else %}
                            {{ article.content|truncatewords:40 }}
                        {% endif %}
                    </p>
                {% endif %}
            {% else %}
                <p class="card-text">
                    {% if article.description %}
                        {{ article.description }}
                    {% else %}
                        {{ article.content|truncatewords:40 }}
                    {% endif %}
                </p>
            {% endflag %}
        </div>
        <div class="card-footer">
            <a class="btn btn-secondary btn-sm" href="{{ article.get_absolute_url }}" title="Read More">Read More</a>
            {% if all_articles %}
                <a class="btn btn-secondary btn-sm" href="{% url 'article-list' %}" title="All Articles">All Articles</a>
            {% endif %}
        </div>
    </div>
</div>

articles/templates/articles/article_detail.html
{% extends "championship/base.html" %}
{% load article %}
{% load cache %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block meta_description %}{% if article.description|striptags %}{{ article.description }}{% else %}{{ article.content|striptags|truncatewords:40 }}{% endif %}{% endblock %}

{% block extrahead %}
    <link href="//cdn.jsdelivr.net/npm/mana-font@latest/css/mana.min.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
    <h1>{{ article.title }}
        <small class="text-muted">by {{ article.author.first_name }} {{ article.author.last_name }}</small>

        {% if perms.articles.change_article %}
            <a href="{% url 'article-update' article.id article.slug %}" class="btn btn-secondary">Edit</a>
        {% endif %}
    </h1>
    {% if article.published_date %}
        <p>Published on {{ article.published_date }}</p>
    {% endif %}


    {% cache 604800 article_content article.id %}
        {{ article.content|article_tags }}
    {% endcache %}

    {% include "decklists/card_modal.html" %}
{% endblock %}

articles/templates/articles/article_draft.html
{% extends 'championship/base.html' %}

{% block title %}My drafts{% endblock %}

{% block content %}
    <h1>My drafts</h1>

    <ul>
        {% for article in articles %}
            <li><a href="{% url 'article-preview' article.id article.slug %}">
                {{article.title}}
            </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

articles/templates/articles/decklist_card.html
<div class="border rounded p-4">
        <h3>{{ decklist.archetype }} <small class="text-muted">by <a href="{{ decklist.player.get_absolute_url }}">{{ decklist.player.get_name_display }}</a></small></h3>
        <p>Format: {{ decklist.collection.get_format_display }}<br>
                Event: <a href="{{ decklist.collection.event.get_absolute_url }}">{{ decklist.collection.event.name }}</a></p>
        <hr class="my-2">
        {% include "decklists/decklist_table.html" with cards_by_section=cards_by_section %}
</div>

articles/templates/articles/update_article.html
{% extends "championship/base.html" %}

{% load crispy_forms_tags %}

{% block extrahead %}
    {{ form.media }}
{% endblock %}

{% block content %}
    <h1>Edit article</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" value="Submit" class="btn btn-secondary">Submit</button>
    </form>
    <p>Need to add some pictures ? <a href="{% url 'article-attachment-create' %}" target="_blank">Upload here</a>
{% endblock %}

articles/templates/articles/upload_attachment.html
{% extends "championship/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
    <h1>Upload article attachment</h1>
    {% crispy form %}
{% endblock %}